### ISSUE TITLE
how to implement the receive ?

### ISSUE THREAD

**Issue by wade-liwei** [blockcypher/libgrin#16]
how to implement the grin-wallet receive -i file1.json with the api  ?

**Comment by wade-liwei** [comment]
https://docs.rs/grin_wallet_api/1.1.0/grin_wallet_api/struct.Foreign.html#method.receive_tx

**Comment by quentinlesceller** [comment]
Hi, you can take a look at https://github.com/blockcypher/libgrin/blob/master/example/secure_owner_api.go#L483. `finalize` is very similar with `receive` so you can just modify the method and that should work.
